### ISSUE TITLE
Small popover Bug

### ISSUE THREAD

**Issue by fleyne** [danieljfarrell/DFColorWell#3]
First, very nice control.

Second, in _handleMouseUpInColorRect you should add (prior creating the popover) a test such as:  
if([_popover isShown]) return;  or  if([_popover isShown]) {[_popover close]; return;}

Otherwise you are creating _popover for every click on the chevron even if the _popover is already displayed. This is visible, in the popover shadow.

**Comment by danieljfarrell** [comment]
Thanks! I will fix it.

Did you notice because of visual effect, or by looking through the code?

To trigger this bug you have to continually click on the chevron. I guess you did that?

![screen shot 2015-03-23 at 20 56 15](https://cloud.githubusercontent.com/assets/112847/6790408/3faf6720-d19f-11e4-8c74-b0a6ac988dff.png)

**Comment by fleyne** [comment]
Yes by clicking few times. The normal behaviour should have closed/opened the popover but did not. Then I realised that the shadow was getting darker.

**Comment by danieljfarrell** [comment]
OK that's fixed. Thanks! Glad someone has found this control useful :+1:
Changes here, 2ce9b0f64d
